  services:
    sync-server:
      build: /volume1/Docker/anysocket/app
      working_dir: /app
      volumes:
        - /volume1/Docker/anysync/sync_data:/app/data
        - /volume1/Docker/anysync/config.js:/app/config.js
      environment:
        - PORT=3000
      ports:
        - "3777:3000"
